import pygame, sys
from pygame import *

smiley=pygame.image.load('smiley.png')
frowny=pygame.image.load('frowny.png')
heart=pygame.image.load('rpg_heart.png')
broken_heart=pygame.image.load('rpg_broken_heart.png')
rock=pygame.image.load('rpg_rock.png')
sparring_sword_sprite=pygame.image.load('rpg_sparring_sword.png')
fire_sword_sprite=pygame.image.load('rpg_fire_sword.png')
fire_sword_sprite_2=pygame.image.load('rpg_fire_sword2.png')
lavender_battleaxe_sprite=pygame.image.load('rpg_lavender_battle_axe.png')
#fully animated
wood_axe_sprite_r=pygame.image.load('rpg_wood_axe.png')
wood_axe_sprite_l=pygame.image.load('rpg_wood_axe_l.png')
wood_axe_sprite_u=pygame.image.load('rpg_wood_axe_u.png')
wood_axe_sprite_d=pygame.image.load('rpg_wood_axe_d.png')
#fully animated
hero_sprite_r1=pygame.image.load('rpg_hero.png')
hero_sprite_r2=pygame.image.load('rpg_hero_frame2.png')
hero_sprite_l1=pygame.image.load('rpg_hero_lframe1.png')
hero_sprite_l2=pygame.image.load('rpg_hero_lframe2.png')
hero_sprite_u1=pygame.image.load('rpg_hero_uframe1.png')
hero_sprite_u2=pygame.image.load('rpg_hero_uframe2.png')
hero_sprite_d1=pygame.image.load('rpg_hero_dframe1.png')
hero_sprite_d2=pygame.image.load('rpg_hero_dframe2.png')
#fully animated
arrow_up_sprite=pygame.image.load('rpg_arrow_up.png')
arrow_down_sprite=pygame.image.load('rpg_arrow_down.png')
arrow_left_sprite=pygame.image.load('rpg_arrow_left.png')
arrow_right_sprite=pygame.image.load('rpg_arrow_right.png')
#fully animated
bullet_up_sprite=pygame.image.load('rpg_bullet_u.png')
bullet_down_sprite=pygame.image.load('rpg_bullet_d.png')
bullet_right_sprite=pygame.image.load('rpg_bullet_r.png')
bullet_left_sprite=pygame.image.load('rpg_bullet_l.png')
#fully animated
zombie_sprite_r1=pygame.image.load('rpg_zombie.png')
zombie_sprite_r2=pygame.image.load('rpg_zombie_rframe2.png')
zombie_sprite_l1=pygame.image.load('rpg_zombie_lframe1.png')
zombie_sprite_l2=pygame.image.load('rpg_zombie_lframe2.png')
#fully animated
skeleton_sprite_l1=pygame.image.load('rpg_skeleton.png')
skeleton_sprite_l2=pygame.image.load('rpg_skeleton_l2.png')
skeleton_sprite_r1=pygame.image.load('rpg_skeleton_r.png')
skeleton_sprite_r2=pygame.image.load('rpg_skeleton_r2.png')
#fully animated
fire_elemental_sprite_r1=pygame.image.load('rpg_fire_elemental_r1.png')
fire_elemental_sprite_r2=pygame.image.load('rpg_fire_elemental_r2.png')
fire_elemental_sprite_l1=pygame.image.load('rpg_fire_elemental_l1.png')
fire_elemental_sprite_l2=pygame.image.load('rpg_fire_elemental_l2.png')
fire_elemental_sprite_attack_r1=pygame.image.load('rpg_fire_elemental_attack_r1.png')
fire_elemental_sprite_attack_r2=pygame.image.load('rpg_fire_elemental_attack_r2.png')
fire_elemental_sprite_attack_l1=pygame.image.load('rpg_fire_elemental_attack_l1.png')
fire_elemental_sprite_attack_l2=pygame.image.load('rpg_fire_elemental_attack_l2.png')
fire_elemental_sprite_attack_u1=pygame.image.load('rpg_fire_elemental_attack_u1.png')
fire_elemental_sprite_attack_u2=pygame.image.load('rpg_fire_elemental_attack_u2.png')
fire_elemental_sprite_attack_d1=pygame.image.load('rpg_fire_elemental_attack_d1.png')
fire_elemental_sprite_attack_d2=pygame.image.load('rpg_fire_elemental_attack_d2.png')
#incomplete animation
cookie_man_sprite_r1=pygame.image.load('rpg_cookie_man.png')
cookie_man_sprite_r1_headless=pygame.image.load('rpg_cookie_man_headless.png')
cookie_sprite=pygame.image.load('rpg_cookie.png')
#
necromancer_sprite_r=pygame.image.load('necromancer_r.png')
necromancer_sprite_l=pygame.image.load('necromancer_l.png')
necromancer_attack_sprite_r=pygame.image.load('necromancer_attack_r.png')
necromancer_attack_sprite_l=pygame.image.load('necromancer_attack_l.png')
#fully animated
wood_bow_sprite_r=pygame.image.load('rpg_bow_r.png')
wood_bow_sprite_l=pygame.image.load('rpg_bow_l.png')
wood_bow_sprite_u=pygame.image.load('rpg_wood_bow_u.png')
wood_bow_sprite_d=pygame.image.load('rpg_wood_bow_d.png')
#fully animated
glock_sprite_r=pygame.image.load('rpg_gun_r.png')
glock_sprite_l=pygame.image.load('rpg_gun_l.png')
glock_sprite_v=pygame.image.load('rpg_glock_v.png')
#fully animated
crossbow_sprite_r = pygame.image.load('rpg_crossbow_right.png')
crossbow_sprite_l = pygame.image.load('rpg_crossbow_left.png')
crossbow_sprite_u = pygame.image.load('rpg_crossbow_u.png')
crossbow_sprite_d = pygame.image.load('rpg_crossbow_d.png')
#not fully animated
fire_bow_sprite_r1 = pygame.image.load('rpg_Fire_bow_r.png')
fire_bow_sprite_r2 = pygame.image.load('rpg_Fire_bow_r2.png')
fire_bow_sprite_l1 = pygame.image.load('rpg_Fire_bow_l.png') 
fire_bow_sprite_l2 = pygame.image.load('rpg_Fire_bow_l2.png')
fire_bow_sprite_u1 = pygame.image.load('rpg_Fire_bow_u.png')
fire_bow_sprite_u2 = pygame.image.load('RPG_Fire_bow_u2.png')
#fully animated
iron_bow_sprite_r=pygame.image.load('rpg_iron_bow_r.png')
iron_bow_sprite_l=pygame.image.load('rpg_iron_bow_l.png')
iron_bow_sprite_u=pygame.image.load('rpg_iron_bow_u.png')
iron_bow_sprite_d=pygame.image.load('rpg_iron_bow_d.png')
#fully animated
platnium_bow_sprite_r=pygame.image.load('rpg_platnium_bow_r.png')
platnium_bow_sprite_l=pygame.image.load('rpg_platnium_bow_l.png')
platnium_bow_sprite_u=pygame.image.load('rpg_platnium_bow_u.png')
platnium_bow_sprite_d=pygame.image.load('rpg_platnium_bow_d.png')
#fully animated
headband_sprite_r=pygame.image.load('rpg_headband_r.png')
headband_sprite_l=pygame.image.load('rpg_headband_l.png')
headband_sprite_u=pygame.image.load('rpg_headband_u.png')
headband_sprite_d=pygame.image.load('rpg_headband_d.png')
#fully animated
iron_helmet_sprite_r=pygame.image.load('rpg_iron_helmet_r.png')
iron_helmet_sprite_l=pygame.image.load('rpg_iron_helmet_l.png')
iron_helmet_sprite_u=pygame.image.load('rpg_iron_helmet_u.png')
iron_helmet_sprite_d=pygame.image.load('rpg_iron_helmet_d.png')
#fully animated
steel_helmet_sprite_r=pygame.image.load('rpg_steel_helmet_r.png')
steel_helmet_sprite_l=pygame.image.load('rpg_steel_helmet_l.png')
steel_helmet_sprite_u=pygame.image.load('rpg_steel_helmet_u.png')
steel_helmet_sprite_d=pygame.image.load('rpg_steel_helmet_d.png')
#fully animated
platinum_helmet_sprite_r=pygame.image.load('rpg_platinum_helmet_r.png')
platinum_helmet_sprite_l=pygame.image.load('rpg_platinum_helmet_l.png')
platinum_helmet_sprite_u=pygame.image.load('rpg_platinum_helmet_u.png')
platinum_helmet_sprite_d=pygame.image.load('rpg_platinum_helmet_d.png')
#fully animated
leather_cap_sprite_r=pygame.image.load('rpg_leather_cap_r.png')
leather_cap_sprite_l=pygame.image.load('rpg_leather_cap_l.png')
leather_cap_sprite_u=pygame.image.load('rpg_leather_cap_u.png')
leather_cap_sprite_d=pygame.image.load('rpg_leather_cap_d.png')
#fully animated
ragged_cloak_sprite_r1=pygame.image.load('rpg_ragged_cloak_r.png')
ragged_cloak_sprite_r2=pygame.image.load('rpg_ragged_cloak_r2.png')
ragged_cloak_sprite_l1=pygame.image.load('rpg_ragged_cloak_l.png')
ragged_cloak_sprite_l2=pygame.image.load('rpg_ragged_cloak_l2.png')
ragged_cloak_sprite_u1=pygame.image.load('rpg_ragged_cloak_u.png')
ragged_cloak_sprite_u2=pygame.image.load('rpg_ragged_cloak_u2.png')
ragged_cloak_sprite_d1=pygame.image.load('rpg_ragged_cloak_d1.png')
ragged_cloak_sprite_d2=pygame.image.load('rpg_ragged_cloak_d2.png')
#fully animated
iron_chestplate_sprite_r=pygame.image.load('rpg_iron_chestplate_r.png')
iron_chestplate_sprite_l=pygame.image.load('rpg_iron_chestplate_l.png')
iron_chestplate_sprite_u1=pygame.image.load('rpg_iron_chestplate_u1.png')
iron_chestplate_sprite_u2=pygame.image.load('rpg_iron_chestplate_u2.png')
iron_chestplate_sprite_d1=pygame.image.load('rpg_iron_chestplate_d1.png')
iron_chestplate_sprite_d2=pygame.image.load('rpg_iron_chestplate_d2.png')
#fully animated
platinum_chestplate_sprite_r=pygame.image.load('rpg_platinum_chestplate_r.png')
platinum_chestplate_sprite_l=pygame.image.load('rpg_platinum_chestplate_l.png')
platinum_chestplate_sprite_u1=pygame.image.load('rpg_platinum_chestplate_u1.png')
platinum_chestplate_sprite_u2=pygame.image.load('rpg_platinum_chestplate_u2.png')
platinum_chestplate_sprite_d1=pygame.image.load('rpg_platinum_chestplate_d1.png')
platinum_chestplate_sprite_d2=pygame.image.load('rpg_platinum_chestplate_d2.png')
#fully animated
iron_greeves_sprite_r1=pygame.image.load('rpg_iron_greeves_r1.png')
iron_greeves_sprite_r2=pygame.image.load('rpg_iron_greeves_r2.png')
iron_greeves_sprite_l1=pygame.image.load('rpg_iron_greeves_l1.png')
iron_greeves_sprite_l2=pygame.image.load('rpg_iron_greeves_l2.png')
iron_greeves_sprite_u1=pygame.image.load('rpg_iron_greeves_u1.png')
iron_greeves_sprite_u2=pygame.image.load('rpg_iron_greeves_u2.png')
iron_greeves_sprite_d1=pygame.image.load('rpg_iron_greeves_d1.png')
iron_greeves_sprite_d2=pygame.image.load('rpg_iron_greeves_d2.png')
#fully animated
steel_greeves_sprite_r1=pygame.image.load('rpg_steel_greeves_r1.png')
steel_greeves_sprite_r2=pygame.image.load('rpg_steel_greeves_r2.png')
steel_greeves_sprite_l1=pygame.image.load('rpg_steel_greeves_l1.png')
steel_greeves_sprite_l2=pygame.image.load('rpg_steel_greeves_l2.png')
steel_greeves_sprite_u1=pygame.image.load('rpg_steel_greeves_u1.png')
steel_greeves_sprite_u2=pygame.image.load('rpg_steel_greeves_u2.png')
steel_greeves_sprite_d1=pygame.image.load('rpg_steel_greeves_d1.png')
steel_greeves_sprite_d2=pygame.image.load('rpg_steel_greeves_d2.png')
#fully animated
platinum_greeves_sprite_r1=pygame.image.load('rpg_platinum_greeves_r1.png')
platinum_greeves_sprite_r2=pygame.image.load('rpg_platinum_greeves_r2.png')
platinum_greeves_sprite_l1=pygame.image.load('rpg_platinum_greeves_l1.png')
platinum_greeves_sprite_l2=pygame.image.load('rpg_platinum_greeves_l2.png')
platinum_greeves_sprite_u1=pygame.image.load('rpg_platinum_greeves_u1.png')
platinum_greeves_sprite_u2=pygame.image.load('rpg_platinum_greeves_u2.png')
platinum_greeves_sprite_d1=pygame.image.load('rpg_platinum_greeves_d1.png')
platinum_greeves_sprite_d2=pygame.image.load('rpg_platinum_greeves_d2.png')
#fully aniamted
steel_chestplate_sprite_r=pygame.image.load('rpg_steel_chestplate_r.png')
steel_chestplate_sprite_l=pygame.image.load('rpg_steel_chestplate_l.png')
steel_chestplate_sprite_u1=pygame.image.load('rpg_steel_chestplate_u1.png')
steel_chestplate_sprite_u2=pygame.image.load('rpg_steel_chestplate_u2.png')
steel_chestplate_sprite_d1=pygame.image.load('rpg_steel_chestplate_d1.png')
steel_chestplate_sprite_d2=pygame.image.load('rpg_steel_chestplate_d2.png')
warrior_emblem=pygame.image.load('rpg_warrior_emblem.png')
ranger_emblem=pygame.image.load('rpg_ranger_emblem.png')
menu_select=pygame.image.load('rpg_menu_select.png')
inventory_select=pygame.image.load('rpg_inventory_select.png')
one_up_sprite=pygame.image.load('rpg_1up.png')
fire_sprite_1=pygame.image.load('rpg_fire_1.png')
fire_sprite_2=pygame.image.load('rpg_fire_2.png')
place_holder_sprite=pygame.image.load('rpg_place_holder.png')